### PR TITLE
closes #43

### LINKED ISSUE #43: data.replace
Fix injecting react component string into html. RegEx is not working over multiple lines.

### PR DESCRIPTION
**Pull request by shachyjr**
Makes id of root component that server-side html will be placed within dynamic -- dependent on user input

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -30,7 +27,8 @@ const render = (req, res) => {
   } else {
     fs.readFile(inputs.html, 'utf8', (err, data) => {
       if (err) throw err;
-      const document = data.replace(/<body>(.*)<\/body>/, `<body><div id="root">${stringComponent}</div>$1</body>`);
+      const regEx = new RegExp(`<div id="${inputs.id}"><\/div>`, 'gi')
+      const document = data.replace(regEx, `<div id="${inputs.id}">${stringComponent}</div>`);
```
Comment (cli53) [inline src/index.js:31]: Nice Job with the RegEx
